# Copyright (C) 2025 Silimate Inc.
#
# Adapted from Yosys wheels
#
# Copyright (C) 2024 Efabless Corporation
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
name: Build and run tests

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    uses: Silimate/actions/.github/workflows/cpp-cmake-ci.yml@v1
    with:
      install-cudd: true
      cmake-generator: Ninja
      apt-packages: >-
        wget cmake gcc tcl-dev tcl-tclreadline libeigen3-dev swig bison flex
        libfl-dev libdwarf-dev libdw-dev libelf-dev elfutils automake
        autotools-dev ninja-build
      macos-setup: |
        brew bundle install

        echo "$(brew --prefix tcl-tk@8)/bin" >> $GITHUB_PATH
        echo "$(brew --prefix flex)/bin" >> $GITHUB_PATH
        echo "$(brew --prefix bison)/bin" >> $GITHUB_PATH
        echo "CMAKE_PREFIX_PATH=$(brew --prefix tcl-tk@8):$(brew --prefix flex):$(brew --prefix bison):$(brew --prefix tcl-readline):$(brew --prefix dwarfutils):$(brew --prefix libelf)" >> $GITHUB_ENV
        echo "CMAKE_INCLUDE_PATH=$(brew --prefix dwarfutils)/include/libdwarf-2:$(brew --prefix libelf)/include/libelf" >> $GITHUB_ENV
